title: Muhammad Ibraheem 
description: Blog by Muhammad Ibraheem Software Engineer

url: http://muhammadibraheem.me
baseurl: "/"
paginate_path: "page:num/"
permalink: /:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: brianmaierjr
   twitter: brianmaierjr
   facebook: brianmaierjr
   email: engr.ibraheemswl@gmail.com

google_analytics: ""
