title: Muhammad Ibraheem 
description: Blog by Muhammad Ibraheem Software Engineer

url: http://muhammadibraheem.github.com
baseurl: "/blog"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: brianmaierjr
   twitter: brianmaierjr
   facebook: brianmaierjr
   email: engr.ibraheemswl@gmail.com

google_analytics: ""
